import type { ServerBuild } from '@remix-run/cloudflare';
import { createPagesFunctionHandler } from '@remix-run/cloudflare-pages';
import { logAccess } from '../app/utils/access-log';
import * as Sentry from '@sentry/cloudflare';

// @ts-ignore because the server build file is generated by `remix vite:build`
import * as serverBuild from '../build/server';

// Cloudflare Pages environment variables
interface CloudflareEnv {
  ASSETS: Fetcher;
  SENTRY_DSN?: string;
  CF_PAGES_BRANCH?: string;
  CF_PAGES_COMMIT_SHA?: string;
  CF_PAGES_URL?: string;
  [key: string]: unknown;
}

/*
 * Create the base handler
 */
const baseHandler = createPagesFunctionHandler({
  build: serverBuild as unknown as ServerBuild,
});

// Sentry middleware - captures errors and performance data
const sentryMiddleware = Sentry.sentryPagesPlugin<CloudflareEnv>((context) => ({
  dsn: context.env.SENTRY_DSN,
  tracesSampleRate: 0.1, // 10% sampling for performance monitoring
  environment: context.env.CF_PAGES_BRANCH === 'main' ? 'production' : 'preview',
  release: `agent8@${context.env.CF_PAGES_COMMIT_SHA?.substring(0, 7) || 'unknown'}`,

  beforeSend(event) {
    // Filter out common noise
    const errorMessage = event.exception?.values?.[0]?.value || '';

    // Ignore aborted requests
    if (errorMessage.includes('AbortError')) {
      return null;
    }

    return event;
  },
}));

// Main request handler with access logging
const handler: PagesFunction<CloudflareEnv> = async (context) => {
  const { request } = context;
  const url = new URL(request.url);
  const method = request.method;
  const path = url.pathname;

  // 🚀 FAST TRACK: Only log API requests, skip everything else
  if (!path.startsWith('/api/') || method === 'OPTIONS') {
    return await baseHandler(context);
  }

  // API request detected - start performance measurement
  const startTime = Date.now();

  // Collect request information for API logging
  const userAgent = request.headers.get('User-Agent');
  const ip =
    request.headers.get('CF-Connecting-IP') ||
    request.headers.get('X-Forwarded-For') ||
    request.headers.get('X-Real-IP') ||
    'unknown';

  // Get or generate request ID
  const requestId =
    request.headers.get('CF-Ray') ||
    request.headers.get('CF-Request-ID') ||
    request.headers.get('X-Request-ID') ||
    crypto.randomUUID();

  let response: Response;
  let statusCode = 200;

  try {
    // Execute the actual handler
    response = await baseHandler(context);
    statusCode = response.status;
  } catch (error) {
    statusCode = 500;
    console.error('Handler error:', error instanceof Error ? error.message : 'Unknown error');
    response = new Response('Internal Server Error', { status: 500 });
  }

  // Calculate response time
  const responseTime = Date.now() - startTime;

  // Determine service name from Cloudflare Pages deployment or fallback to 'agent8'
  const getServiceName = (): string => {
    if (context.env?.CF_PAGES_URL) {
      try {
        const pagesUrl = new URL(context.env.CF_PAGES_URL);
        const hostname = pagesUrl.hostname;

        if (hostname.endsWith('.pages.dev')) {
          const withoutPagesDev = hostname.split('.pages.dev')[0];
          const parts = withoutPagesDev.split('.');

          // If there are multiple parts (deployment-id.project-name), take the last part
          return parts.length > 1 ? parts[parts.length - 1] : parts[0];
        }
      } catch {
        // Ignore parsing errors and fall back to default
      }
    }

    return 'agent8';
  };

  // Log API request to Cloudflare Queue
  await logAccess(
    {
      method,
      path,
      query: url.search || undefined,
      statusCode,
      responseTime,
      ip,
      userAgent: userAgent || 'unknown',
      serviceName: getServiceName(),
      requestId,
    },
    context.env,
  ).catch((error) => {
    console.error('Access logging failed:', error instanceof Error ? error.message : 'Unknown error');
  });

  return response;
};

// Export as middleware chain: Sentry wraps all subsequent handlers
export const onRequest = [sentryMiddleware, handler];
